#!/usr/bin/env php
<?php

declare(strict_types=1);

namespace ImboReleaser;

use GuzzleHttp\Client as GuzzleHttpClient;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Middleware;
use ImboReleaser\Console\Application;
use ImboReleaser\Exception\RuntimeException;
use ImboReleaser\GitHub\Client;
use ImboReleaser\GitHub\Middleware\Retry;
use ImboReleaser\GitHub\TokenResolver;
use Throwable;

use function fwrite;
use function sprintf;

use const PHP_EOL;
use const STDERR;

$autoloaders = [
    __DIR__.'/../../autoload.php',
    __DIR__.'/../autoload.php',
    __DIR__.'/vendor/autoload.php',
];
$autoloader = null;
foreach ($autoloaders as $file) {
    if (file_exists($file)) {
        $autoloader = $file;
        break;
    }
}

if (null === $autoloader) {
    throw new RuntimeException('Unable to locate autoload.php file.');
}

require $autoloader;

try {
    $token = (new TokenResolver())->getGitHubToken();
    if (null === $token) {
        throw new RuntimeException('Failed to resolve the required GitHub API token. Please make sure to set the "GITHUB_TOKEN" environment variable or authenticate using the GitHub CLI.');
    }

    $retry = new Retry();
    $handlerStack = HandlerStack::create();
    $handlerStack->push(Middleware::retry($retry->decide(...), $retry->delay(...)));

    $httpClient = new GuzzleHttpClient([
        'handler' => $handlerStack,
        'base_uri' => 'https://api.github.com',
        'headers' => [
            'Accept' => 'application/vnd.github+json',
            'Authorization' => sprintf('Bearer %s', $token),
            'X-GitHub-Api-Version' => '2022-11-28',
            'User-Agent' => 'imbo/releaser',
        ],
    ]);
    $gitHubClient = new Client($httpClient);
    $app = new Application($gitHubClient);

    exit($app->run());
} catch (Throwable $e) {
    fwrite(STDERR, sprintf('Error: %s', $e->getMessage()).PHP_EOL);
    exit(1);
}
